//#############################################################################
//
// FILE:   
//
// TITLE: dfadf
//        dfs
//        
//
//#############################################################################
// $Pelab Release: $
// $Release Date: $
// $Copyright: $
//#############################################################################


#include "tida_01606_SDFM.h"



//! \brief Setup eCAP to generate clock for SDMF ( APWM mode), 20Mhz
//! \param[in] void
//! There is no parameter here
//!
int16_t tida_01606_eCap_setup_for_SDFM()
{
    // Select ECAP 0 on Mux0 and enable
    EALLOW; 
    OutputXbarRegs.OUTPUT1MUX0TO15CFG.bit.MUX0 = OUTPUT_ECAP;
    OutputXbarRegs.OUTPUT1MUXENABLE.bit.MUX0   = OUTPUT_ENABLE;
    EDIS;

    // setup GPIO24 as outputxbar
    EALLOW;


    GpioCtrlRegs.GPAPUD.bit.GPIO24     = GPIO_DIS_PULL_UP;
    GpioCtrlRegs.GPADIR.bit.GPIO24     = GPIO_OUTPUT_MODE;
    GpioCtrlRegs.GPAMUX2.bit.GPIO24    = GPIO_OUTPUT_xBar;

    EDIS;
    // Setup APWM mode on eCAP peripheral
    ECap1Regs.ECCTL2.bit.CAP_APWM   = ECAP_APWM_ENABLE;

    // set period and compare registers
    ECap1Regs.CAP1                  = ECAP_PERIOD -1;
    ECap1Regs.CAP2                  = ECAP_PERIOD>>1;

    // set next duty cycle to 50%
    ECap1Regs.CAP4                  = ECAP_PERIOD>>1;
    ECap1Regs.CAP3                  = ECAP_PERIOD -1;
    ECap1Regs.ECCLR.all             = 0xFF;     //clear pending interrupt
    ECap1Regs.ECEINT.bit.CTR_EQ_CMP = 1;

    // start counters

    ECap1Regs.ECCTL2.bit.TSCTRSTOP = 1;

    return 1;
}


//! \brief Setup ePWM11 for syncing the SD filter Window,
//! be sure that counter mode is not up-down
//! \param[in] void
//! There is no parameter here
//!
 int16_t tida_01606_ePWM11_setup_for_SDFM()
{
    // setup time base of ePWM11
    

    //when using ePWM11 or ePWM12 for SDFM Data filter synchronization
    //, user must ensure that ONLY ONE CMPC or CMPD event 
    // will be generated per PWM timer period






    //synchronized pulse is generated by software 
    //epwm5, epwm7, epwm10


    // CMPC and CMPD are used 
    // to send the SDFM sync pulse to the filter





    //CMPA is used to read the SDFM register


    return 1;



}



//! \brief Setup ePWM11 for syncing the SD filter Window
//! \param[in] void
//! There is no parameter here
//!
 int16_t tida_01606_GPIO_setup_for_SDFM()
{
    
    return 1;
}





//! \brief Setup ePWM11 for syncing the SD filter Window
//! \param[in] void
//! There is no parameter here
//!
int16_t tida_01606_SDFM_setup_input_control()
{
    return 1;

}






//! \brief Setup ePWM11 for syncing the SD filter Window
//! \param[in] void
//! There is no parameter here
//!
 int16_t tida_01606_SDFM_setup_sinc_filter()
{
    return 1;

}













//! \brief Setup ePWM11 for syncing the SD filter Window
//! \param[in] void
//! There is no parameter here
//!
int16_t tida_01606_SDFM_setup_comp_module()
{
    return 1;
}







//
// End of file



//







